server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

spring.sql.init.mode: always
spring.jpa.properties.hibernate.format_sql: true
logging.level.org.hibernate.SQL: DEBUG

security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: ${JWT_SECRET_KEY}