server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuariosdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

spring.sql.init.mode: always
spring.jpa.properties.hibernate.format_sql: true
logging.level.org.hibernate.SQL: DEBUG

